import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
      // Loose TS config (strict: false, noImplicitAny: false) means most `any`
      // here are deliberate workarounds for the auto-generated Supabase types.ts
      // (tables/JSON columns not in the generated types). Surface them as warnings
      // instead of build-breaking errors.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  {
    // Edge functions are Deno code, not type-checked by this toolchain. The Deno
    // `// @ts-ignore` imports, `any`s, and control-char sanitization regexes are
    // intentional; node-eslint can't meaningfully type them.
    files: ["supabase/functions/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "no-control-regex": "off",
    },
  },
  {
    // shadcn primitives are regenerated by the CLI — do not hand-edit.
    files: ["src/components/ui/**"],
    rules: {
      "@typescript-eslint/no-empty-object-type": "off",
      "react-refresh/only-export-components": "off",
    },
  },
);
